### PR TITLE
Additional I/O routines

### PR DESCRIPTION
**Pull request by roblatham00**
Looks like mpiP only wraps a handful of MPI-IO routines.  Here are a couple more.

I would have added all the MPI-IO routines, but when I tried to add others, I'll often get an error in the wrapper script, despite modifying both mpi.io.protos.txt and the opaqueInArgDict of make-wrpapers.py:

```
   Wrapped MPI_File_close
Traceback (most recent call last):
  File "./make-wrappers.py", line 1697, in <module>
    main()
  File "./make-wrappers.py", line 1687, in main
    GenerateWrappers()
  File "./make-wrappers.py", line 1540, in GenerateWrappers
    CreateWrapper(funct, olist)
  File "./make-wrappers.py", line 1312, in CreateWrapper
    olist.append(currBasetype + ' ')
UnboundLocalError: local variable 'currBasetype' referenced before assignment
```

I am a caveman python programmer and unable to make sense of that error yet.

### CODE REVIEW

**Comment by cchambreau** [comment]
If you can provide an example of an MPI function causing this error, that would be great.

**Comment by roblatham00** [comment]
Sure.  Here's my attempt at adding `MPI_File_delete`, which triggered that error:

```
% git diff
diff --git a/make-wrappers.py b/make-wrappers.py
index 699a71e0..6a74b647 100755
--- a/make-wrappers.py
+++ b/make-wrappers.py
@@ -222,6 +222,7 @@ opaqueInArgDict = {
   ("MPI_File_close", "fh"):"MPI_File",
   ("MPI_File_open", "comm"):"MPI_Comm",
   ("MPI_File_open", "info"):"MPI_Info",
+  ("MPI_File_delete", "info"):"MPI_Info",
   ("MPI_File_preallocate", "fh"):"MPI_File",
   ("MPI_File_set_size", "fh"):"MPI_File",
   ("MPI_File_read", "fh"):"MPI_File",
diff --git a/mpi.io.protos.txt b/mpi.io.protos.txt
index b2995ff9..e0409b8f 100644
--- a/mpi.io.protos.txt
+++ b/mpi.io.protos.txt
@@ -3,6 +3,8 @@ int MPI_File_close (MPI_File *fh)
 
 int MPI_File_open (MPI_Comm comm, mpip_const_char_t *filename, int amode, MPI_Info info, MPI_File *fh)
 
+int MPI_File_delete (mpip_const_char_t *filename, MPI_Info info);
+
 int MPI_File_preallocate (MPI_File fh, MPI_Offset size)
 
 int MPI_File_set_size (MPI_File fh, MPI_Offset size)
```

**Comment by cchambreau** [comment]
This worked for me, but I haven't had a chance to track down why it wasn't failing with other string cases:

diff --git a/make-wrappers.py b/make-wrappers.py
index 699a71e..cab2564 100755
--- a/make-wrappers.py
+++ b/make-wrappers.py
@@ -222,6 +222,7 @@ opaqueInArgDict = {
   ("MPI_File_close", "fh"):"MPI_File",
   ("MPI_File_open", "comm"):"MPI_Comm",
   ("MPI_File_open", "info"):"MPI_Info",
+  ("MPI_File_delete", "info"):"MPI_Info",
   ("MPI_File_preallocate", "fh"):"MPI_File",
   ("MPI_File_set_size", "fh"):"MPI_File",
   ("MPI_File_read", "fh"):"MPI_File",
@@ -1274,6 +1275,7 @@ def CreateWrapper(funct, olist):

     #  Iterate through the arguments for this function
     opaqueFound = 0
+    currBasetype = ""
     for i in fdict[funct].paramConciseList:

         if ( doOpaqueXlate is True and fdict[funct].paramDict[i].basetype in xlateTargetTypes ) :
@@ -1302,6 +1304,7 @@ def CreateWrapper(funct, olist):
                 1 == fdict[funct].paramDict[i].pointerLevel ) :
             stringVarNames.append(i);
             decl += "  char *c_" + i + " = NULL;\n";
+            currBasetype = fdict[funct].paramDict[i].basetype
         else:
             #  Not translating this variable
             currBasetype = fdict[funct].paramDict[i].basetype

**Comment by cchambreau** [comment]
This worked for me, but I haven't looked into why this didn't fail for other strings yet:

diff --git a/make-wrappers.py b/make-wrappers.py
index 699a71e..58e06b0 100755
--- a/make-wrappers.py
+++ b/make-wrappers.py
@@ -222,6 +222,7 @@ opaqueInArgDict = {
   ("MPI_File_close", "fh"):"MPI_File",
   ("MPI_File_open", "comm"):"MPI_Comm",
   ("MPI_File_open", "info"):"MPI_Info",
+  ("MPI_File_delete", "info"):"MPI_Info",
   ("MPI_File_preallocate", "fh"):"MPI_File",
   ("MPI_File_set_size", "fh"):"MPI_File",
   ("MPI_File_read", "fh"):"MPI_File",
@@ -1302,6 +1303,7 @@ def CreateWrapper(funct, olist):
                 1 == fdict[funct].paramDict[i].pointerLevel ) :
             stringVarNames.append(i);
             decl += "  char *c_" + i + " = NULL;\n";
+            currBasetype = fdict[funct].paramDict[i].basetype
         else:
             #  Not translating this variable
             currBasetype = fdict[funct].paramDict[i].basetype

**Comment by cchambreau** [comment]
Here what worked for me, but I haven't checked why it isn't failing for other strings:

```
diff --git a/make-wrappers.py b/make-wrappers.py
index 699a71e..58e06b0 100755
--- a/make-wrappers.py
+++ b/make-wrappers.py
@@ -222,6 +222,7 @@ opaqueInArgDict = {
   ("MPI_File_close", "fh"):"MPI_File",
   ("MPI_File_open", "comm"):"MPI_Comm",
   ("MPI_File_open", "info"):"MPI_Info",
+  ("MPI_File_delete", "info"):"MPI_Info",
   ("MPI_File_preallocate", "fh"):"MPI_File",
   ("MPI_File_set_size", "fh"):"MPI_File",
   ("MPI_File_read", "fh"):"MPI_File",
@@ -1302,6 +1303,7 @@ def CreateWrapper(funct, olist):
                 1 == fdict[funct].paramDict[i].pointerLevel ) :
             stringVarNames.append(i);
             decl += "  char *c_" + i + " = NULL;\n";
+            currBasetype = fdict[funct].paramDict[i].basetype
         else:
             #  Not translating this variable
             currBasetype = fdict[funct].paramDict[i].basetype
```

**Comment by roblatham00** [comment]
Thanks!  I've updated my branch to include your bug fix and a few more MPI-IO routines.  I did not add the ordered, shared, non-blocking, and non-blocking collective routines yet.  The next time I see a code using them will be the first time...

**Pull request merged**
